Program File Format Version : 1.6  MechType: 739(HH4-01)  TotalAxis: 6  AuxAxis: 0
     'USAGE:9806_MMH_VIZsetBRANCH(1, 1)
     '203, VIZ SET BRANCH: Branch Name, Branch Exit No.
     V501$="203"+","+STR$(V490%)+","+STR$(V491%)
     CALL 9823_MMH_SEND
     'ANSER
     CALL 9824_MMH_RECV
     IF V503$<>"203" THEN
     PRINT #0, "ERROR : 203 CMD ERROR"
     STOP
     ENDIF
     'IF V504$<>"2105" THEN
     'PRINT #0, "ERROR : 203 IPC ERROR"
     'STOP
     'ENDIF
     END
